### ISSUE TITLE
Training Large-Scale Tesseract OCR Model for Uchen Script

### ISSUE THREAD

**Issue by tenzinyonten** [OpenPecha/image-to-text#40]
**Description**

 Train Tesseract OCR model on multiple large-scale Uchen script datasets (~4M images) for improved Tibetan text recognition.

**Implementation:**

2.	Data preprocessing and format conversion
3.	Training file generation
4.	Model training and optimisation

**Subtasks:**

- [ ] Consolidate all datasets and verify completeness 
- [ ] Convert text files to ground truth format
- [ ] Configure Makefile parameters
- [ ] 	Generate box and lstmf files
- [ ] 	Execute and monitor training process

**Completion Criteria: **

Successfully train a Tesseract model for Uchen script recognition

**Card Reviewer: **

- [ ] @ta4tsering

**Comment by tenzinyonten** [comment]
The Karmapa8 dataset currently doesn’t have a predefined data split. I reached out to @ta4tsering , and he confirmed he will prepare it and provide it by today.

**Comment by ta4tsering** [comment]
I have updated the blog as well as the hugging face with three new repos of Uchan data with data distribution or the data split. 

https://huggingface.co/datasets/openpecha/OCR-NorbuketakaNumbers
https://huggingface.co/datasets/openpecha/OCR-Karmapa8
https://huggingface.co/datasets/openpecha/OCR-KhyentseWangpo
